### ISSUE TITLE
Fix: Make the UI Responsive

### ISSUE THREAD

**Issue by 777ahesh** [777ahesh/Sangeet#11]
Currently the UI is not Mobile responsive make it Responsive.

Anyone who  wants to work on this issue comment below I will Assign it to you

**Comment by 0xk4b1r** [comment]
Hey @777ahesh

I want to contribute to this project.
You can assign this issue to me

Thanks.

**Comment by 777ahesh** [comment]
@kabir0x23 You can start working on this issue

**Comment by 0xk4b1r** [comment]
@777ahesh 

Why you are using both bootstraps and CSS?

**Comment by 777ahesh** [comment]
As this is a beginner friendly repo I have kept the flexibility to use css and bootstrap.
@kabir0x23  you can use any one of them to make the UI Layout responsive css-grids or bootstrap

**Comment by 0xk4b1r** [comment]
> As this is a beginner friendly repo I have kept the flexibility to use css and bootstrap. @kabir0x23 you can use any one of them to make the UI Layout responsive css-grids or bootstrap

same functionalities can be formed by using one of from both, no need to use both
beginners can get confused

i will use CSS  to make this site responsive

**Comment by 777ahesh** [comment]
Sure Happy Coding

**Comment by 0xk4b1r** [comment]
Hey @777ahesh , you can assign this issue to someone else, 
Not able to solve this issue till Monday,

**Comment by ghost** [comment]
hey @777ahesh could you assign this issue to me?

**Comment by 777ahesh** [comment]
@VodkaCranberry Go Ahead You can Start Working on this issue
