### ISSUE TITLE
New Feature: Create a Signup Form UI for Sangeet Website

### ISSUE THREAD

**Issue by 777ahesh** [777ahesh/Sangeet#13]
Comment Below If you want to work on this issue

**Comment by kabir0x23** [comment]
Hey @777ahesh 

I want to contribute to this project.
You can assign this issue to me

Thanks.

**Comment by nitoC** [comment]
can I be assigned this?

**Comment by 777ahesh** [comment]
@nitoC  you can start working on this issue now. Happy coding..
