### ISSUE TITLE
create a login form

### ISSUE THREAD

**Issue by ramubethi** [777ahesh/Sangeet#16]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I would like to work on this  [...]

**Describe the solution you'd like**

**Additional context**

**Comment by 777ahesh** [comment]
@Ramubethi  You can start working on this issue. Happy Coding...

**Comment by codesmith25103** [comment]
Can you assign me this issue?

**Comment by 777ahesh** [comment]
@codesmith25103 you can start working on this issue you have to create a seperate login.html file
