### ISSUE TITLE
Frontend Design

### ISSUE THREAD

**Issue by Pranavsg-200** [777ahesh/Sangeet#17]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I would like to work on this  [...]

**Describe the solution you'd like**

**Additional context**

**Comment by codesmith25103** [comment]
I want to work on this issue. Please assign me this?

**Comment by Ishikasaraf20** [comment]
can you assign this issue to me i can work on it

**Comment by 777ahesh** [comment]
@Ishikasaraf20 @codesmith25103  you can work on some other issue
