### ISSUE TITLE
New Component: 404 Error Page

### ISSUE THREAD

**Issue by 777ahesh** [777ahesh/Sangeet#22]
**Is your feature request related to a problem? Please describe.**
In this issue you have to work on creating the UI of 404 Error Page.

**Describe the solution you'd like**
You have to create a separate ErrorPage.html and ErrorPage.css for this issue

Comment Below so that I can assign It to you

**Comment by Chandak-Keshav** [comment]
Can you please assign me this @777ahesh .
I have an idea to use HTML,CSS and Jquery to give an error page a 3D sort of view.

**Comment by 777ahesh** [comment]
@Chandak-Keshav  Go ahead You can start working on this issue

**Comment by 777ahesh** [comment]
@Chandak-Keshav  what is  the progress regarding the issue

**Comment by Chandak-Keshav** [comment]
Almost done.
I have made an astronaut using CSS properties with 404 error message. Now I just need to make it floating as if it is in space. Will be done in 3-4 hours.
