### ISSUE TITLE
Modify the color scheme of the website and add more images

### ISSUE THREAD

**Issue by SonamGiri9150** [777ahesh/Sangeet#34]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I would like to work on this  [...]

**Describe the solution you'd like**

**Additional context**

**Comment by SonamGiri9150** [comment]
I would like to work on this 
Please assign me to this task

**Comment by 777ahesh** [comment]
@SonamGiri9150 go ahead you can start working on this issue

**Comment by singhkaran202** [comment]
Hello @777ahesh, I'd love to work on this, if that's OK.
Could you please assign me this issue?

**Comment by 777ahesh** [comment]
@singhkaran202  this issue is already assigned you can choose some other issue or create a new one if you find some enhancement required in the project.
